### ISSUE TITLE
No module name jinja2

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/bread#156]
Hi @saemideluxe,

my nightly builds are failing since March 15:
https://lbs.solidcharity.com/projects/basx/basxconnect/package/basxconnect-devenv/#main_fedora/37/amd64

the error message is:

```
[00:02:49]   File "/home/django/bread/basxbread/utils/jinja2.py", line 4, in <module>
[00:02:49]     from jinja2.sandbox import SandboxedEnvironment
[00:02:49] ModuleNotFoundError: No module named 'jinja2'
```

I suspect this is the commit that caused it:
https://github.com/basxsoftwareassociation/bread/commit/f8c53b0931fac1d2297f5b94c5b7bb61ab3c15ce

You dropped `docxtpl` from `setup.py`, and that did download `jinja2` as a dependency.

I hope this helps!

**Comment by saemideluxe** [comment]
Yeah, I noticed Github actions failing but didnt look at it yet. Thanks for the investigation and the details!

**Comment by saemideluxe** [comment]
That commit was not the problem, I just removed a duplicate entry (it should only be installed with one of the extra dependencies). But the problem was that docxtpl had a dependency to jinja2 which I did not declare explicit. That should be fixed by now. There are still some tests failing in Github CI, but I will fix that a bit later.

**Comment by saemideluxe** [comment]
Test should now also be passing again.
